/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Source;

import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author user
 */
public class Barcode extends javax.swing.JFrame {

    /**
     * Creates new form Barcode
     */
    public Barcode() {
        initComponents();
        intilize();
    }

    private void intilize() {

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        BarcodeTbl = new javax.swing.JTextField();
        ItemNameTbl = new javax.swing.JTextField();
        RateTbl = new javax.swing.JTextField();
        QtyTbl = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Item Name", "Rate", "MRP"
            }
        ));
        jScrollPane1.setViewportView(ItemTable);

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Close");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BarcodeTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BarcodeTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BarcodeTblKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BarcodeTblKeyReleased(evt);
            }
        });

        ItemNameTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ItemNameTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ItemNameTblKeyPressed(evt);
            }
        });

        RateTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RateTbl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        QtyTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        QtyTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QtyTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QtyTblKeyPressed(evt);
            }
        });

        AddBtn.setBackground(new java.awt.Color(0, 102, 102));
        AddBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Print");
        AddBtn.setBorder(null);
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Barcode");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Rate");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Qty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarcodeTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemNameTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RateTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(QtyTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RateTbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BarcodeTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ItemNameTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(QtyTbl)
                    .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BarcodeTblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarcodeTblKeyReleased

    }//GEN-LAST:event_BarcodeTblKeyReleased


    private void BarcodeTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarcodeTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Statement statement;
                try (Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", "")) {
                    statement = (Statement) connection.createStatement();
                    ResultSet result = statement.executeQuery("SELECT * FROM `stock_enrty` WHERE Barcode ='" + BarcodeTbl.getText() + "'");
                    while (result.next()) {

                        ItemNameTbl.setText(result.getString(7));
                        RateTbl.setText(result.getString(10));

                        QtyTbl.requestFocus();

                        ////////////////////////////////////////////////
                        try {
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection connection1 = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", "");
                            Statement statement1 = (Statement) connection1.createStatement();
                            ResultSet result1 = statement1.executeQuery("Select * from purchase WHERE Barcode ='" + BarcodeTbl.getText() + "'");
                            while (result1.next()) {
                                RateTbl.setText(result1.getString(10));

                            }
                        } catch (ClassNotFoundException | SQLException e34) {
                            JOptionPane.showMessageDialog(this, e34);
                        }

                    }
                    result.next();
                }
                statement.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            QtyTbl.requestFocus();
        }

    }//GEN-LAST:event_BarcodeTblKeyPressed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed

        // Retrieve input values from text fields
        String barcode = BarcodeTbl.getText();
        String itemName = ItemNameTbl.getText();
        String rate = RateTbl.getText();
        String qty = QtyTbl.getText();

        // Input validation checks
        if (barcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Barcode!");
        } else if (itemName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Item Name!");
        } else if (rate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Rate!");
        } else if (qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Quantity!");
        } else {
            // If all fields are filled, proceed with database insertion
            try {
                // Load MySQL JDBC driver
                Class.forName("com.mysql.jdbc.Driver");

                // Establish a connection to the database
                Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", "");

                // Prepare SQL insert query
                String query = "INSERT INTO barcode (Barcode, Item, rate, qty) VALUES (?, ?, ?, ?)";
                java.sql.PreparedStatement ps = connection.prepareStatement(query);

                // Set parameters for the prepared statement
                ps.setString(1, barcode);
                ps.setString(2, itemName);
                ps.setString(3, rate);
                ps.setString(4, qty);

                // Execute the update
                int rowsInserted = ps.executeUpdate();
                if (rowsInserted > 0) {
                    //JOptionPane.showMessageDialog(this, "Item added successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to create new item", "Quick ledger", JOptionPane.ERROR_MESSAGE);
                }

                // Close PreparedStatement and Connection
                ps.close();
                connection.close();

                // Print Invoice after insertion
                Print_Invoice(barcode, itemName, rate, qty);

            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Driver not found", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error inserting data: " + e.getMessage(), "Quick ledger Error", JOptionPane.ERROR_MESSAGE);
            }

        }
        Print_Invoice();

    }//GEN-LAST:event_AddBtnActionPerformed
    void Print_Invoice(String barcode, String item, String rate, String qty) {
        try {
            // Load JDBC driver (assuming this is only needed once per application session)
            Class.forName("com.mysql.jdbc.Driver");

            // Establish database connection
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", "");

            // Load JasperDesign from JRXML file
            File jrxmlFile = new File("src\\Report\\SingleB.jrxml");  // Adjust path as necessary
            JasperDesign jd = JRXmlLoader.load(jrxmlFile.getAbsolutePath());

            // Set parameters if needed
            HashMap<String, Object> para = new HashMap<>();
            // para.put("invoiceno", InvoiceNo); // Uncomment and set parameters if needed

            // Compile JasperReport
            JasperReport jr = JasperCompileManager.compileReport(jd);

            // Fill the report
            JasperPrint jp = JasperFillManager.fillReport(jr, para, connection);

            // Display report in a JFrame
            JRViewer viewer = new JRViewer(jp);
            JFrame frame = new JFrame("Barcode");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.add(viewer);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH); // Full screen
            frame.setVisible(true);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error generating report: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            // Log the exception
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            // Log the exception
        }

        Delete_Print_Invoice();
    }

    void Delete_Print_Invoice() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", "");
            Statement statement = connection.createStatement();
            String query = "DELETE FROM barcode";
            statement.executeUpdate(query);
            statement.close();
            connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting data: " + e.getMessage());
        }
    }

    void Print_Invoice() {
        String barcode = BarcodeTbl.getText();
        String item = ItemNameTbl.getText();
        String rate = RateTbl.getText();
        String qty = QtyTbl.getText();

        try (Connection connection1 = java.sql.DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", ""); PreparedStatement ps = (PreparedStatement) connection1.prepareStatement("INSERT INTO `barcode` (Barcode, Item, rate, qty) VALUES (?, ?, ?, ?)")) {
            ps.setString(1, barcode);
            ps.setString(2, item);
            ps.setString(3, rate);
            ps.setString(4, qty);

            ps.executeUpdate();
            Print_Invoice(); // Call method to print the customer copy
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }


    private void QtyTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            AddBtn.doClick();
        }
    }//GEN-LAST:event_QtyTblKeyPressed

    private void ItemNameTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ItemNameTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            BarcodeTbl.requestFocus();
        }
        // Get the text entered in jTextField1
        String inputText = ItemNameTbl.getText().trim();

        // Check if inputText is valid
        if (!inputText.equals("Select") && !inputText.isEmpty()) {
            try {
                // Load MySQL driver
                Class.forName("com.mysql.jdbc.Driver");

                // Establish connection to the database
                Connection connection = DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
                Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery("SELECT * FROM `stock_enrty` WHERE ItemName Like '%" + inputText + "%' OR Barcode Like '%" + inputText + "%'");

                // Use a DefaultTableModel to populate jTable1
                DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
                model.setRowCount(0);  // Clear previous rows

                // Loop through the result set and populate the table
                while (result.next()) {
                    //String groupName = result.getString(8);
                    String barcode = result.getString(3);
                    String salePrice = result.getString(7);
                    String purchaseRate = result.getString(10);
                    String qty = result.getString(13);

                    // Add each row to the table model
                    model.addRow(new Object[]{barcode, salePrice, purchaseRate, qty});
                }

                // Close the connection
                result.close();
                statement.close();
                connection.close();

            } catch (ClassNotFoundException | SQLException e) {
                // Display error message in case of exception
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            // Handle the case where the input is not valid
            //JOptionPane.showMessageDialog(this, "Please enter a valid item name.");
        }
        ItemTable.setVisible(true); // This shows the table again
    }//GEN-LAST:event_ItemNameTblKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barcode.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barcode.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barcode.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barcode.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barcode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField BarcodeTbl;
    private javax.swing.JTextField ItemNameTbl;
    private javax.swing.JTable ItemTable;
    private javax.swing.JTextField QtyTbl;
    private javax.swing.JTextField RateTbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
