/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Source;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import mondrian.olap.DriverManager;

/**
 *
 * @author USER
 */
public class DeleteData extends javax.swing.JFrame {

    /**
     * Creates new form DeleteData
     */
    public DeleteData() {
        initComponents();
         intilize();
    }

    private void intilize() {

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Dalete All Data");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(521, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // Load MySQL JDBC Driver
            Class.forName("com.mysql.jdbc.Driver");

            // List of tables to delete from
            try ( // Connect to the database
                    java.sql.Connection connection1 = (java.sql.Connection) java.sql.DriverManager.getConnection("jdbc:mysql://127.0.0.1/grocery_database", "root", "")) {
                // List of tables to delete from
                String[] tables = {
                    "accountinfo", "bankaccount", "barcode", "budget_analysis",
                    "businessanalysis", "cash_balance", "ccloandetail",
                    "ccsaccount", "companyinfo","customerdue","customer_statement","dailybackup_p","daily_allowence","daily_profit_memo","daily_report","director","employee_appoint","errorinformation",
                    "establishment","invtemp","invprint_p5","invprint_p4","invprint_p3","invprint_p1","invprint_p2","invprint","invoice_count","invmaster","invaudit","interest","groupname","loandetail",
                    "logininfo","memberinformation","memberinformation_tesco","member_information","member_ledger","merbershipcard","merchantbank","moneyreceipt","moneyreceiptchqdetail","money_expense",
                    "money_received","monthly_backup_print","monthly_memo_profit","movementanalysis","options","order_advance_datagrid","order_master","order_name_master","order_no","order_temp_datagrid",
                    "party_balance","party_due","paymentstatement","profitandlossprint","profit_memo","profit_share","purchase","purchasereturntemp","purchase_hold","purchase_statement","qmaster","recall","recall_purchase_hold",
                    "returnpayment","return_audit","return_audit","return_purchase","return_temp","roll","roll_grid","salary","salary_change_temp","salary_temp","saledaily","salemonthly",
                    "findpurchasesupplair","invtempsave","journal","ladger","leave_sanction","loanbalance","saleyearly","sale_return","searchproduct","searchproductreturn","serial","stockbarcode",
                    "stockreport","stockview","stock_master","stock_report","stock_statement","stock_temp","supplairinfo","supplier_balance","supplier_due","supplier_statement"
                        
                };      // Loop through each table and execute a delete command
                for (String table : tables) {
                    String deleteQuery = "DELETE FROM " + table;
                    try (PreparedStatement preparedStatement = (PreparedStatement) connection1.prepareStatement(deleteQuery)) {
                        int rowsDeleted = preparedStatement.executeUpdate();
                        System.out.println("Deleted " + rowsDeleted + " rows from " + table);
                    }
                }
                // Close the connection
            }
            JOptionPane.showMessageDialog(rootPane, "Data successfully deleted from all specified tables.");
            System.out.println("Data successfully deleted from all specified tables.");

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
