/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Source;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PriceChange extends javax.swing.JFrame {

    /**
     * Creates new form PriceChange
     */
    public PriceChange() {
        initComponents();
        intilize();
    }

    private void intilize() {

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarcodeTbl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StockQtyTbl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CostPriceTbl = new javax.swing.JTextField();
        SalePriceTbl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VatTbl = new javax.swing.JTextField();
        PriceChangeBtn = new javax.swing.JButton();
        GroupNameTbl = new javax.swing.JTextField();
        ProductNameTbl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Price Change");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        BarcodeTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BarcodeTbl.setForeground(new java.awt.Color(0, 102, 102));
        BarcodeTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BarcodeTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        BarcodeTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BarcodeTblKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Barcode");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Group Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Product Name");

        StockQtyTbl.setEditable(false);
        StockQtyTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StockQtyTbl.setForeground(new java.awt.Color(0, 102, 102));
        StockQtyTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StockQtyTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stock Qty");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cost Price");

        CostPriceTbl.setEditable(false);
        CostPriceTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CostPriceTbl.setForeground(new java.awt.Color(0, 102, 102));
        CostPriceTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostPriceTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        SalePriceTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SalePriceTbl.setForeground(new java.awt.Color(0, 102, 102));
        SalePriceTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SalePriceTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        SalePriceTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SalePriceTblKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sale Price");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vat");

        VatTbl.setEditable(false);
        VatTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        VatTbl.setForeground(new java.awt.Color(0, 102, 102));
        VatTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VatTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        PriceChangeBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PriceChangeBtn.setForeground(new java.awt.Color(0, 153, 153));
        PriceChangeBtn.setText("Price Change");
        PriceChangeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PriceChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceChangeBtnActionPerformed(evt);
            }
        });

        GroupNameTbl.setEditable(false);
        GroupNameTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GroupNameTbl.setForeground(new java.awt.Color(0, 102, 102));
        GroupNameTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GroupNameTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        ProductNameTbl.setEditable(false);
        ProductNameTbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProductNameTbl.setForeground(new java.awt.Color(0, 102, 102));
        ProductNameTbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ProductNameTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarcodeTbl)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StockQtyTbl)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CostPriceTbl)
                    .addComponent(SalePriceTbl)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VatTbl)
                    .addComponent(PriceChangeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(GroupNameTbl)
                    .addComponent(ProductNameTbl))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarcodeTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(GroupNameTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(ProductNameTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockQtyTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CostPriceTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalePriceTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VatTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PriceChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(443, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BarcodeTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarcodeTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int count = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
                Statement statement = (Statement) connection.createStatement();
                java.sql.ResultSet result = statement.executeQuery("SELECT * FROM `stock_enrty` WHERE Barcode ='" + BarcodeTbl.getText() + "'");
                while (result.next()) {
                    count = 1;
                    GroupNameTbl.setText(result.getString(8));
                    ProductNameTbl.setText(result.getString(7));
                    SalePriceTbl.setText(result.getString(13));
                    CostPriceTbl.setText(result.getString(10));
                    // Status = result.getString(14);

                    SalePriceTbl.requestFocus();

                    ////////////////////////////////////////////////
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection connection1 = (Connection) DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
                        Statement statement1 = (Statement) connection1.createStatement();
                        java.sql.ResultSet result1 = statement1.executeQuery("Select * from purchase WHERE Barcode ='" + BarcodeTbl.getText() + "'");
                        while (result1.next()) {
                            CostPriceTbl.setText(result1.getString(8));
                            SalePriceTbl.setText(result1.getString(10));
                            StockQtyTbl.setText(result1.getString(7));
                        }
                    } catch (Exception e34) {
                        JOptionPane.showMessageDialog(this, e34);
                    }

                    ////////////////////////////////////////////////
                }
                result.next();
                connection.close();
                statement.close();
                if (count == 0) {
                    GroupNameTbl.setText(null);
                    ProductNameTbl.setText(null);
                    CostPriceTbl.setText(null);
                    SalePriceTbl.setText(null);
                }
            } catch (Exception ex) {
                System.out.println(ex);
            }
            SalePriceTbl.requestFocus();
        }
    }//GEN-LAST:event_BarcodeTblKeyPressed

    private void SalePriceTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalePriceTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            PriceChangeBtn.doClick();
    }//GEN-LAST:event_SalePriceTblKeyPressed

    private void PriceChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceChangeBtnActionPerformed
        if (SalePriceTbl.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter New Sale Price");
        } else {
            Connection connection = null;
            PreparedStatement ps = null;
            try {
                // Load MySQL JDBC driver
                Class.forName("com.mysql.cj.jdbc.Driver"); // Correct driver class name for newer versions

                // Establish the connection to the database
                connection = DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");

                // SQL query to update SalePrice in the database
                // Adjust the WHERE clause to match your actual table's schema
                String sql = "UPDATE purchase SET SalePrice = ? WHERE Barcode = ?"; // Replace Barcode with your unique identifier column

                // Prepare the SQL statement
                ps = (PreparedStatement) connection.prepareStatement(sql);

                // Set the parameters in the prepared statement
                ps.setString(1, SalePriceTbl.getText().trim());

                // Replace this with the actual value for filtering the rows
                String barcode = BarcodeTbl.getText().trim(); // Assuming you use Barcode as the identifier
                ps.setString(2, barcode); // Ensure this matches the data type of the column in the WHERE clause

                // Execute the update
                int rowsAffected = ps.executeUpdate();

                // Check if the update was successful
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Sale Price Updated");
                } else {
                    JOptionPane.showMessageDialog(this, "No records were updated");
                }

                // Clear the text fields
                StockQtyTbl.setText(null);
                SalePriceTbl.setText(null);
                BarcodeTbl.setText(null);
                GroupNameTbl.setText(null);
                ProductNameTbl.setText(null);
                CostPriceTbl.setText(null);

            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Database driver not found: " + e.getMessage());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "SQL error: " + e.getMessage());
            } finally {
                // Clean up resources
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    if (connection != null) {
                        connection.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error closing resources: " + e.getMessage());
                }
            }
        }

    }//GEN-LAST:event_PriceChangeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PriceChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarcodeTbl;
    private javax.swing.JTextField CostPriceTbl;
    private javax.swing.JTextField GroupNameTbl;
    private javax.swing.JButton PriceChangeBtn;
    private javax.swing.JTextField ProductNameTbl;
    private javax.swing.JTextField SalePriceTbl;
    private javax.swing.JTextField StockQtyTbl;
    private javax.swing.JTextField VatTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
