/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Source;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mondrian.olap.Query;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class ProfitLossReport extends javax.swing.JFrame {

    String TotalBalanceSum,
            DiscountSum,
            SaleReturnAmount,
            NetSale,
            total_buy_cost,
            Gross_profit, Other_Income, Servicing_Charge, Commission, Other_services_charge, Total_gross_profit, Monthly_Bills, Entertainment, Carrying_charge, Other_Expense, Discount, Payment_Commission, Yearly_Bills, Salary, Bank_Interest, Depreciation, Daily_Expenditure, Purchasing_extra_Expenditure, Total_Expense, netprofitorloss, Profit_Payment,
            Rest_Amount;

    /**
     * Creates new form ProfitLossReport
     */
    public ProfitLossReport() {
        initComponents();
        intilize();
    }

    private void intilize() {

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Fromdate = new com.toedter.calendar.JDateChooser();
        Todate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profite Loss Perort", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Find");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fromdate, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Todate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fromdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Todate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Date selectedDate = Fromdate.getDate();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String FromDate = dateFormat.format(selectedDate);

            Date selectedDate1 = Todate.getDate();
            String ToDate = dateFormat.format(selectedDate1);

            String Query = "SELECT COALESCE(SUM(a.TotalBlance), 0) AS TotalBalanceSum, COALESCE(SUM(a.DiscountTk), 0) AS DiscountSum, COALESCE(SUM(sr.Amount), 0) AS SaleReturnAmount, COALESCE(SUM(a.TotalBlance) - (SUM(a.DiscountTk) + SUM(sr.Amount)), 0) AS NetSale, (SELECT COALESCE(SUM(subquery.single_buy_cost), 0) FROM (SELECT invaudit.qty, purchase.Rate, invaudit.qty * purchase.Rate AS single_buy_cost FROM invaudit INNER JOIN purchase ON invaudit.Barcode = purchase.Barcode) AS subquery) AS total_buy_cost, COALESCE(SUM(a.TotalBlance) - (SUM(a.DiscountTk) + SUM(sr.Amount)), 0) - COALESCE((SELECT SUM(subquery.single_buy_cost) FROM (SELECT invaudit.qty, purchase.Rate, invaudit.qty * purchase.Rate AS single_buy_cost FROM invaudit INNER JOIN purchase ON invaudit.Barcode = purchase.Barcode) AS subquery), 0) AS Gross_profit, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Others (Income)' AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Other_Income, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Servicing Charge' AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Servicing_Charge, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Commission' AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Commission, COALESCE((SELECT SUM(Amount) FROM paymentstatement WHERE Reasone IN ('Others (Income)', 'Servicing Charge', 'Commission') AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) AS Other_services_charge, COALESCE((SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone IN ('Others (Income)', 'Servicing Charge', 'Commission') AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) + COALESCE(SUM(a.TotalBlance) - (SUM(a.DiscountTk) + SUM(sr.Amount)), 0) - COALESCE((SELECT SUM(subquery.single_buy_cost) FROM (SELECT invaudit.qty, purchase.Rate, invaudit.qty * purchase.Rate AS single_buy_cost FROM invaudit INNER JOIN purchase ON invaudit.Barcode = purchase.Barcode) AS subquery), 0) AS Total_gross_profit, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Monthly Bills' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Monthly_Bills, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Entertainment' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Entertainment, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Carrying Charge' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Carrying_charge, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Other Expense' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Other_Expense, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Discount' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Discount, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Commission' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Payment_Commission, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Yearly Bills' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Yearly_Bills, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Salary' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Salary, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Bank Interest' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Bank_Interest, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Depreciation' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Depreciation, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Daily Expenditure' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Daily_Expenditure, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone = 'Purchasing Extra Expenditure' AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Purchasing_extra_Expenditure, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone IN ('Monthly Bills', 'Entertainment', 'Carrying Charge', 'Other Expense', 'Yearly Bills', 'Commision', 'Discount' ,'Purchasing Extra Expenditure', 'Daily Expenditure', 'Depreciation', 'Bank Interest', 'Salary') AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Total_Expense, COALESCE(SUM(a.TotalBlance) - (SUM(a.DiscountTk) + SUM(sr.Amount)), 0) + COALESCE((SELECT SUM(Amount) FROM paymentstatement WHERE Reasone IN ('Others (Income)', 'Servicing Charge', 'Commission') AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) - COALESCE((SELECT SUM(subquery.single_buy_cost) FROM ( SELECT invaudit.qty, purchase.Rate, invaudit.qty * purchase.Rate AS single_buy_cost FROM invaudit INNER JOIN purchase ON invaudit.Barcode = purchase.Barcode ) AS subquery), 0) - COALESCE((SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone IN ('Monthly Bills', 'Entertainment', 'Carrying Charge', 'Other Expense', 'Yearly Bills', 'Commision', 'Discount' ,'Purchasing Extra Expenditure', 'Daily Expenditure', 'Depreciation', 'Bank Interest', 'Salary') AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) AS netprofitorloss, (SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Status = 'Payment' AND Reasone = 'Daily Bank' AND Date BETWEEN " + FromDate + " AND " + ToDate + ") AS Profit_Payment, COALESCE(SUM(a.TotalBlance) - (SUM(a.DiscountTk) + SUM(sr.Amount)), 0) + COALESCE((SELECT SUM(Amount) FROM paymentstatement WHERE Reasone IN ('Others (Income)', 'Servicing Charge', 'Commission') AND Status = 'Recive' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) - COALESCE((SELECT SUM(subquery.single_buy_cost) FROM ( SELECT invaudit.qty, purchase.Rate, invaudit.qty * purchase.Rate AS single_buy_cost FROM invaudit INNER JOIN purchase ON invaudit.Barcode = purchase.Barcode ) AS subquery), 0) - COALESCE((SELECT COALESCE(SUM(Amount), 0) FROM paymentstatement WHERE Reasone IN ('Monthly Bills', 'Entertainment', 'Carrying Charge', 'Other Expense', 'Yearly Bills', 'Commision', 'Discount' ,'Purchasing Extra Expenditure', 'Daily Expenditure', 'Depreciation', 'Bank Interest', 'Salary') AND Status = 'Payment' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) - COALESCE((SELECT SUM(Amount) FROM paymentstatement WHERE Status = 'Payment' AND Reasone = 'Daily Bank' AND Date BETWEEN " + FromDate + " AND " + ToDate + "), 0) AS Rest_Amount FROM invaudit a LEFT JOIN (SELECT sr.invoiceNo, SUM(sr.Amount) AS Amount FROM sale_return sr GROUP BY sr.invoiceNo) sr ON a.invoiceNo = sr.invoiceNo WHERE a.cdate BETWEEN " + FromDate + " AND " + ToDate + ";";
System.out.println(Query);            
//code start //
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
                Statement statement = (Statement) connection.createStatement();
                ResultSet result = statement.executeQuery(Query);
                while (result.next()) {
                    TotalBalanceSum = result.getString(1);
                    DiscountSum = result.getString(2);
                    SaleReturnAmount = result.getString(3);
                    NetSale = result.getString(4);
                    total_buy_cost = result.getString(5);
                    Gross_profit = result.getString(6);
                    Other_Income = result.getString(7);
                    Servicing_Charge = result.getString(8);
                    Commission = result.getString(9);
                    Other_services_charge = result.getString(10);
                    Total_gross_profit = result.getString(11);
                    Monthly_Bills = result.getString(12);
                    Entertainment = result.getString(13);
                    Carrying_charge = result.getString(14);
                    Other_Expense = result.getString(15);
                    Discount = result.getString(16);
                    Payment_Commission = result.getString(17);
                    Yearly_Bills = result.getString(18);
                    Salary = result.getString(19);
                    Bank_Interest = result.getString(20);
                    Depreciation = result.getString(21);
                    Daily_Expenditure = result.getString(22);
                    Purchasing_extra_Expenditure = result.getString(23);
                    Total_Expense = result.getString(24);
                    netprofitorloss = result.getString(25);
                    Profit_Payment = result.getString(26);
                    Rest_Amount = result.getString(27);

                }
                result.next();
                connection.close();
                statement.close();

            } catch (Exception ex) {

            }
        } catch (Exception e) {

        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
            PreparedStatement ps = (PreparedStatement) connection.prepareStatement("UPDATE profitandlossprint SET TotalBalanceSum = ?, DiscountSum = ?, SaleReturnAmount = ?, NetSale = ?, total_buy_cost = ?, Gross_profit = ?, Other_Income = ?, Servicing_Charge = ?, Commission = ?, Other_services_charge = ?, Total_gross_profit = ?, Monthly_Bills = ?, Entertainment = ?, Carrying_charge = ?, Other_Expense = ?, Discount = ?, Payment_Commission = ?, Yearly_Bills = ?, Salary = ?, Bank_Interest = ?, Depreciation = ?, Daily_Expenditure = ?, Purchasing_extra_Expenditure = ?, Total_Expense = ?, netprofitorloss = ?, Profit_Payment = ?, Rest_Amount = ?;");
            ps.setString(1, TotalBalanceSum);
            ps.setString(2, DiscountSum);
            ps.setString(3, SaleReturnAmount);
            ps.setString(4, NetSale);
            ps.setString(5, total_buy_cost);
            ps.setString(6, Gross_profit);
            ps.setString(7, Other_Income);
            ps.setString(8, Servicing_Charge);
            ps.setString(9, Commission);
            ps.setString(10, Other_services_charge);
            ps.setString(11, Total_gross_profit);
            ps.setString(12, Monthly_Bills);
            ps.setString(13, Entertainment);
            ps.setString(14, Carrying_charge);
            ps.setString(15, Other_Expense);
            ps.setString(16, Discount);
            ps.setString(17, Payment_Commission);
            ps.setString(18, Yearly_Bills);
            ps.setString(19, Salary);
            ps.setString(20, Bank_Interest);
            ps.setString(21, Depreciation);
            ps.setString(22, Daily_Expenditure);
            ps.setString(23, Purchasing_extra_Expenditure);
            ps.setString(24, Total_Expense);
            ps.setString(25, netprofitorloss);
            ps.setString(26, Profit_Payment);
            ps.setString(27, Rest_Amount);
            ps.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // code end //
         
          try {
    // Load JDBC driver (assuming this is only needed once per application session)
    Class.forName("com.mysql.jdbc.Driver");

    // Establish database connection
    Connection connection = DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");

    // Load JasperDesign from JRXML file
    File jrxmlFile = new File("src\\Report\\ProfitandLoss.jrxml");  // Adjust path as necessary
    JasperDesign jd = JRXmlLoader.load(jrxmlFile.getAbsolutePath());

    // Set parameters if needed
    HashMap<String, Object> para = new HashMap<>();
    // para.put("invoiceno", InvoiceNo); // Uncomment and set parameters if needed

    // Compile JasperReport
    JasperReport jr = JasperCompileManager.compileReport(jd);

    // Fill the report
    JasperPrint jp = JasperFillManager.fillReport(jr, para, connection);

    // Display report in a JFrame
    JRViewer viewer = new JRViewer(jp);
    JFrame frame = new JFrame("Invoice");
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.add(viewer);
    frame.setExtendedState(JFrame.MAXIMIZED_BOTH); // Full screen
    frame.setVisible(true);

} catch (JRException ex) {
    JOptionPane.showMessageDialog(null, "Error generating report: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
              // Log the exception
} catch (ClassNotFoundException | SQLException ex) {
    JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
              // Log the exception
}
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfitLossReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfitLossReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfitLossReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfitLossReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfitLossReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fromdate;
    private com.toedter.calendar.JDateChooser Todate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
