/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Source;

import com.mysql.cj.xdevapi.Statement;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SupplierCretor extends javax.swing.JFrame {

    /**
     * Creates new form LedgerCretor
     */
    public SupplierCretor() {
        initComponents();
        intilize();
    }

    private void intilize() {

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ledgernameTbl = new javax.swing.JTextField();
        accounttypeCMB = new javax.swing.JComboBox<>();
        addressTbl = new javax.swing.JTextField();
        mobileTbl = new javax.swing.JTextField();
        openingbalanceTbl = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Account Type");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Ledger Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Mobile No");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Opening Balance");

        ledgernameTbl.setBackground(new java.awt.Color(102, 255, 255));
        ledgernameTbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ledgernameTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ledgernameTblKeyPressed(evt);
            }
        });

        accounttypeCMB.setBackground(new java.awt.Color(0, 255, 51));
        accounttypeCMB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        accounttypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier" }));
        accounttypeCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accounttypeCMBActionPerformed(evt);
            }
        });
        accounttypeCMB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accounttypeCMBKeyPressed(evt);
            }
        });

        addressTbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addressTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressTblKeyPressed(evt);
            }
        });

        mobileTbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mobileTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobileTblKeyPressed(evt);
            }
        });

        openingbalanceTbl.setBackground(new java.awt.Color(204, 204, 255));
        openingbalanceTbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        openingbalanceTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                openingbalanceTblKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(openingbalanceTbl)
                        .addComponent(mobileTbl)
                        .addComponent(addressTbl, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ledgernameTbl, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(accounttypeCMB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 256, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accounttypeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ledgernameTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openingbalanceTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (accounttypeCMB.getSelectedItem().toString().isEmpty() || ledgernameTbl.getText().isEmpty() || addressTbl.getText().isEmpty() || mobileTbl.getText().isEmpty() || openingbalanceTbl.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill in all fields", "Quick ledger", JOptionPane.ERROR_MESSAGE);
} else if (!openingbalanceTbl.getText().matches("\\d+") || !mobileTbl.getText().matches("\\d+")) {
    JOptionPane.showMessageDialog(null, "Opening balance and mobile fields should contain only numbers", "Quick ledger", JOptionPane.ERROR_MESSAGE);
} else {
    int Ladger_Found = 0;
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
        java.sql.Statement statement = (java.sql.Statement) connection.createStatement();
        ResultSet result = statement.executeQuery("SELECT * FROM `accountinfo` WHERE AccountType = '" + accounttypeCMB.getSelectedItem().toString() + "' and LadgerName = '" + ledgernameTbl.getText() + "'");
        while (result.next()) {
            Ladger_Found = 1;
        }
        result.next();
        connection.close();

        statement.close();

    } catch (Exception ex) {
    }
    if (Ladger_Found == 1) {
        JOptionPane.showMessageDialog(this, ledgernameTbl.getText() + "! is also found please write a different name.");
    } else {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
            java.sql.PreparedStatement ps = (java.sql.PreparedStatement) connection.prepareStatement("INSERT INTO accountinfo (AccountType, LadgerName,Address,Mobile,OpenBalance)Values(?,?,?,?,?)");
            ps.setString(1, accounttypeCMB.getSelectedItem().toString());
            ps.setString(2, ledgernameTbl.getText());
            ps.setString(3, addressTbl.getText());
            ps.setString(4, mobileTbl.getText());
            ps.setString(5, openingbalanceTbl.getText());
            ps.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {  
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://192.168.0.108/grocery_database", "root", "");
            com.mysql.jdbc.PreparedStatement ps = (com.mysql.jdbc.PreparedStatement) connection.prepareStatement("INSERT INTO ladger (AccountType, Name,Address,Mobile,Blance)Values(?,?,?,?,?)");
            ps.setString(1, accounttypeCMB.getSelectedItem().toString());
            ps.setString(2, ledgernameTbl.getText());
            ps.setString(3, addressTbl.getText());
            ps.setString(4, mobileTbl.getText());
            ps.setString(5, openingbalanceTbl.getText());
            ps.executeUpdate();
            ledgernameTbl.setText(null);
            addressTbl.setText(null);
            mobileTbl.setText(null);
            openingbalanceTbl.setText(null);
            JOptionPane.showMessageDialog(this, "Ladger Create Successfully");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void accounttypeCMBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accounttypeCMBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            ledgernameTbl.requestFocus();
    }//GEN-LAST:event_accounttypeCMBKeyPressed

    private void ledgernameTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ledgernameTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            addressTbl.requestFocus();
    }//GEN-LAST:event_ledgernameTblKeyPressed

    private void addressTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            mobileTbl.requestFocus();
    }//GEN-LAST:event_addressTblKeyPressed

    private void mobileTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            openingbalanceTbl.requestFocus();
    }//GEN-LAST:event_mobileTblKeyPressed

    private void openingbalanceTblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openingbalanceTblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jButton1.doClick();
    }//GEN-LAST:event_openingbalanceTblKeyPressed

    private void accounttypeCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accounttypeCMBActionPerformed

    }//GEN-LAST:event_accounttypeCMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierCretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierCretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierCretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierCretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierCretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accounttypeCMB;
    private javax.swing.JTextField addressTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ledgernameTbl;
    private javax.swing.JTextField mobileTbl;
    private javax.swing.JTextField openingbalanceTbl;
    // End of variables declaration//GEN-END:variables
}
